import { MenuItem, Order, Feedback, InventoryItem, User, LoyaltyReward } from '@/types';

// Mock User Data
export const DEMO_USER: User = {
  id: 'user-1',
  name: 'Demo User',
  email: 'demo@smartcafe.com',
  phone: '+91 98765 43210',
  role: 'customer',
  loyaltyPoints: 450,
  loyaltyTier: 'Silver',
  createdAt: new Date('2024-01-15'),
};

export const DEMO_ADMIN: User = {
  id: 'admin-1',
  name: 'Café Manager',
  email: 'admin@smartcafe.com',
  phone: '+91 98765 43211',
  role: 'admin',
  loyaltyPoints: 0,
  loyaltyTier: 'Bronze',
  createdAt: new Date('2023-01-01'),
};

// Mock Menu Items
export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'item-1',
    name: 'Latte Coffee',
    description: 'Smooth espresso with steamed milk and light foam',
    price: 120,
    category: 'Coffee',
    image: 'https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=400',
    rating: 4.5,
    reviews: 234,
    available: true,
    bestseller: true,
    veg: true,
    preparationTime: 5,
  },
  {
    id: 'item-2',
    name: 'Cappuccino',
    description: 'Classic Italian coffee with equal parts espresso, milk, and foam',
    price: 130,
    category: 'Coffee',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=400',
    rating: 4.7,
    reviews: 189,
    available: true,
    bestseller: true,
    veg: true,
    preparationTime: 5,
  },
  {
    id: 'item-3',
    name: 'Classic Burger',
    description: 'Juicy beef patty with lettuce, tomato, cheese, and special sauce',
    price: 180,
    category: 'Burger',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
    rating: 4.6,
    reviews: 312,
    available: true,
    bestseller: true,
    veg: false,
    preparationTime: 15,
  },
  {
    id: 'item-4',
    name: 'Veg Burger',
    description: 'Crispy veggie patty with fresh vegetables and mayo',
    price: 150,
    category: 'Burger',
    image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400',
    rating: 4.3,
    reviews: 156,
    available: true,
    bestseller: false,
    veg: true,
    preparationTime: 12,
  },
  {
    id: 'item-5',
    name: 'Margherita Pizza',
    description: 'Classic pizza with tomato sauce, mozzarella, and fresh basil',
    price: 250,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
    rating: 4.8,
    reviews: 421,
    available: true,
    bestseller: true,
    veg: true,
    preparationTime: 20,
  },
  {
    id: 'item-6',
    name: 'Pepperoni Pizza',
    description: 'Loaded with pepperoni, cheese, and Italian herbs',
    price: 320,
    category: 'Pizza',
    image: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=400',
    rating: 4.7,
    reviews: 298,
    available: true,
    bestseller: false,
    veg: false,
    preparationTime: 20,
  },
  {
    id: 'item-7',
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice with no added sugar',
    price: 80,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400',
    rating: 4.4,
    reviews: 167,
    available: true,
    bestseller: false,
    veg: true,
    preparationTime: 3,
  },
  {
    id: 'item-8',
    name: 'Mango Smoothie',
    description: 'Creamy mango smoothie with yogurt and honey',
    price: 110,
    category: 'Drinks',
    image: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=400',
    rating: 4.6,
    reviews: 201,
    available: true,
    bestseller: true,
    veg: true,
    preparationTime: 4,
  },
  {
    id: 'item-9',
    name: 'French Fries',
    description: 'Crispy golden fries with seasoning',
    price: 90,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400',
    rating: 4.5,
    reviews: 289,
    available: true,
    bestseller: true,
    veg: true,
    preparationTime: 8,
  },
  {
    id: 'item-10',
    name: 'Nachos Supreme',
    description: 'Tortilla chips with cheese sauce, salsa, and jalapeños',
    price: 140,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=400',
    rating: 4.4,
    reviews: 178,
    available: true,
    bestseller: false,
    veg: true,
    preparationTime: 10,
  },
  {
    id: 'item-11',
    name: 'Chocolate Brownie',
    description: 'Warm chocolate brownie with vanilla ice cream',
    price: 120,
    category: 'Dessert',
    image: 'https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=400',
    rating: 4.9,
    reviews: 445,
    available: true,
    bestseller: true,
    veg: true,
    preparationTime: 6,
  },
  {
    id: 'item-12',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with coffee-soaked layers',
    price: 150,
    category: 'Dessert',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400',
    rating: 4.7,
    reviews: 267,
    available: true,
    bestseller: false,
    veg: true,
    preparationTime: 5,
  },
  {
    id: 'item-13',
    name: 'Espresso',
    description: 'Strong, rich shot of Italian espresso',
    price: 80,
    category: 'Coffee',
    image: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400',
    rating: 4.6,
    reviews: 145,
    available: true,
    bestseller: false,
    veg: true,
    preparationTime: 3,
  },
  {
    id: 'item-14',
    name: 'Chicken Wings',
    description: 'Spicy crispy chicken wings with ranch dip',
    price: 200,
    category: 'Snacks',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400',
    rating: 4.5,
    reviews: 223,
    available: true,
    bestseller: false,
    veg: false,
    preparationTime: 18,
  },
  {
    id: 'item-15',
    name: 'Iced Coffee',
    description: 'Chilled coffee with milk and ice',
    price: 100,
    category: 'Coffee',
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400',
    rating: 4.4,
    reviews: 198,
    available: true,
    bestseller: false,
    veg: true,
    preparationTime: 4,
  },
];

// Mock Inventory Data
export const INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Coffee Beans',
    category: 'Beverages',
    currentStock: 25,
    unit: 'kg',
    minStockLevel: 10,
    lastRestocked: new Date('2025-03-18'),
    usageRate: 3.5,
  },
  {
    id: 'inv-2',
    name: 'Milk',
    category: 'Dairy',
    currentStock: 40,
    unit: 'liters',
    minStockLevel: 20,
    lastRestocked: new Date('2025-03-19'),
    usageRate: 12,
  },
  {
    id: 'inv-3',
    name: 'Burger Buns',
    category: 'Bakery',
    currentStock: 150,
    unit: 'pieces',
    minStockLevel: 50,
    lastRestocked: new Date('2025-03-20'),
    usageRate: 45,
  },
  {
    id: 'inv-4',
    name: 'Cheese',
    category: 'Dairy',
    currentStock: 8,
    unit: 'kg',
    minStockLevel: 5,
    lastRestocked: new Date('2025-03-17'),
    usageRate: 2.5,
  },
  {
    id: 'inv-5',
    name: 'Tomatoes',
    category: 'Vegetables',
    currentStock: 12,
    unit: 'kg',
    minStockLevel: 8,
    lastRestocked: new Date('2025-03-20'),
    usageRate: 4,
  },
  {
    id: 'inv-6',
    name: 'Lettuce',
    category: 'Vegetables',
    currentStock: 6,
    unit: 'kg',
    minStockLevel: 10,
    lastRestocked: new Date('2025-03-19'),
    usageRate: 3,
  },
];

// Loyalty Rewards
export const LOYALTY_REWARDS: LoyaltyReward[] = [
  {
    id: 'reward-1',
    title: 'Free Coffee',
    description: 'Get any coffee of your choice',
    pointsCost: 200,
    discountType: 'fixed',
    discountValue: 150,
    icon: 'coffee',
  },
  {
    id: 'reward-2',
    title: '10% Off',
    description: 'Get 10% off on your next order',
    pointsCost: 150,
    discountType: 'percentage',
    discountValue: 10,
    icon: 'local-offer',
  },
  {
    id: 'reward-3',
    title: 'Free Dessert',
    description: 'Complimentary dessert with any order',
    pointsCost: 250,
    discountType: 'fixed',
    discountValue: 120,
    icon: 'cake',
  },
  {
    id: 'reward-4',
    title: '20% Off',
    description: 'Save 20% on orders above ₹500',
    pointsCost: 300,
    discountType: 'percentage',
    discountValue: 20,
    icon: 'star',
  },
  {
    id: 'reward-5',
    title: 'Free Burger',
    description: 'Get a classic burger for free',
    pointsCost: 350,
    discountType: 'fixed',
    discountValue: 180,
    icon: 'fastfood',
  },
  {
    id: 'reward-6',
    title: 'VIP Discount',
    description: '30% off on your entire bill',
    pointsCost: 500,
    discountType: 'percentage',
    discountValue: 30,
    icon: 'workspace-premium',
  },
];
